#!/usr/bin/env bash
# Typecheck the app's Kotlin against the real Android platform, without Gradle
# or an Android SDK install.
#
# This exists because Kotlin type errors were otherwise only discoverable by
# waiting for a CI build — one bug cost a three-minute round trip, and the error
# it produced ("operator '==' cannot be applied to 'String?' and 'Long'") is
# exactly what this script reports, at the same line and column.
#
# Usage: android/scripts/typecheck-kotlin.sh
# Cache:  .kotlincheck/ (gitignored); ~200 MB on first run, reused after.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CACHE="${KOTLIN_CHECK_CACHE:-$HOME/.kotlincheck}"
KOTLIN_VERSION=1.9.24          # must match android/build.gradle.kts
PLATFORM_ZIP=platform-34-ext7_r03.zip   # compileSdk 34
SRC="$ROOT/android/app/src/main/java"

mkdir -p "$CACHE"
cd "$CACHE"

fetch() { # fetch <url> <dest>
  [ -s "$2" ] || { echo "[typecheck] downloading $(basename "$2")"; curl -sSL -m 900 -o "$2" "$1"; }
}

# Kotlin compiler distribution. The Maven Central kotlin-compiler jar is not
# self-contained (fails with NoClassDefFoundError: gnu/trove/THashMap), so the
# full distribution is required.
if [ ! -f kotlinc/lib/kotlin-compiler.jar ]; then
  fetch "https://github.com/JetBrains/kotlin/releases/download/v$KOTLIN_VERSION/kotlin-compiler-$KOTLIN_VERSION.zip" kotlin.zip
  unzip -q -o kotlin.zip
fi

fetch "https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/$KOTLIN_VERSION/kotlin-stdlib-$KOTLIN_VERSION.jar" kotlin-stdlib.jar
fetch "https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.26.2/commons-compress-1.26.2.jar" commons-compress.jar

# android.jar straight from Google's SDK repository — the same stub jar the
# Android Gradle plugin compiles against.
if [ ! -s android-34.jar ]; then
  fetch "https://dl.google.com/android/repository/$PLATFORM_ZIP" platform.zip
  python3 - <<'PY'
import zipfile
z = zipfile.ZipFile('platform.zip')
name = next(n for n in z.namelist() if n.endswith('android.jar'))
open('android-34.jar', 'wb').write(z.read(name))
PY
  rm -f platform.zip
fi

# R is generated by AAPT in a real build. Synthesise it from the resources so
# the typecheck can resolve R.string.* / R.id.* / R.layout.* references.
mkdir -p gen/com/soundwave/app
python3 - "$ROOT/android/scripts/check-resources.py" "$ROOT/android" > gen/com/soundwave/app/R.java <<'PY'
import glob, os, re, sys
res = os.path.join(sys.argv[2], 'app/src/main/res')
strings = set()
for p in glob.glob(os.path.join(res, 'values*', '*.xml')):
    strings |= set(re.findall(r'<string name="(\w+)"', open(p, encoding='utf-8').read()))
ids = set()
for p in glob.glob(os.path.join(res, '**', '*.xml'), recursive=True):
    ids |= set(re.findall(r'@\+id/(\w+)', open(p, encoding='utf-8').read()))
layouts = {os.path.splitext(os.path.basename(p))[0]
           for p in glob.glob(os.path.join(res, 'layout*', '*.xml'))}
mipmaps = {os.path.splitext(os.path.basename(p))[0]
           for p in glob.glob(os.path.join(res, 'mipmap*', '*'))
           if os.path.isfile(p)}
drawables = {os.path.splitext(os.path.basename(p))[0]
             for p in glob.glob(os.path.join(res, 'drawable*', '*'))
             if os.path.isfile(p)}
def block(name, values, base):
    if not values: return ''
    body = '\n'.join(f'        public static final int {v} = 0x{base+i:08x};'
                     for i, v in enumerate(sorted(values)))
    return f'    public static final class {name} {{\n{body}\n    }}\n'
print('package com.soundwave.app;\npublic final class R {')
print(block('string', strings, 0x7f030000), end='')
print(block('id', ids, 0x7f020000), end='')
print(block('layout', layouts, 0x7f010000), end='')
print(block('mipmap', mipmaps, 0x7f040000), end='')
print(block('drawable', drawables, 0x7f050000), end='')
print('}')
PY

mkdir -p ext
javac -nowarn -d ext gen/com/soundwave/app/R.java

OUT="$(mktemp -d)"
trap 'rm -rf "$OUT"' EXIT

echo "[typecheck] kotlinc $KOTLIN_VERSION vs android-34"
java -jar kotlinc/lib/kotlin-compiler.jar \
  -classpath "android-34.jar:kotlin-stdlib.jar:commons-compress.jar:ext" \
  -jvm-target 17 -d "$OUT" -nowarn \
  $(find "$SRC" -name '*.kt')

echo "[typecheck] OK — $(find "$OUT" -name '*.class' | wc -l) classes"
